destination: ./_site
auto:        false
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date
navigation:
- text: home
  url: /index.html
- text: contact
  url: /contact.html
- text: links
  url: /links.html
